"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { ROLES, type Role } from "@/lib/roles";

type AdminUser = { id: string; name: string; email: string; role: Role; status: "active" | "inactive"; last_login: string | null };
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const date = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Never";

export default function AdminUsersClient() {
  const [users, setUsers] = useState<AdminUser[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [formError, setFormError] = useState(""), [saving, setSaving] = useState(false), [showPassword, setShowPassword] = useState(false), [target, setTarget] = useState<AdminUser | null>(null), [passwordTarget, setPasswordTarget] = useState<AdminUser | null>(null), [editTarget, setEditTarget] = useState<AdminUser | null>(null);
  const addDialog = useRef<HTMLDialogElement>(null), deleteDialog = useRef<HTMLDialogElement>(null), resetDialog = useRef<HTMLDialogElement>(null), editDialog = useRef<HTMLDialogElement>(null);
  const load = async () => { setLoading(true); const response = await fetch("/api/admin/users", { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error || "Unable to load users."); else { setUsers(body.users); setError(""); } setLoading(false); };
  useEffect(() => { void load(); }, []);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; setSaving(true); setError(""); setFormError(""); const values = new FormData(form); const data = { name: String(values.get("name") || ""), email: String(values.get("email") || ""), password: String(values.get("password") || ""), role: String(values.get("role") || ""), status: String(values.get("status") || "") }; const response = await fetch("/api/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) { setFormError(body.error || "Unable to add user."); return; } setUsers((current) => [body.user, ...current]); setShowPassword(false); addDialog.current?.close(); form.reset(); };
  const remove = async () => { if (!target) return; setSaving(true); const response = await fetch("/api/admin/users", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: target.id }) }); const body = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) { setError(body.error || "Unable to delete user."); deleteDialog.current?.close(); return; } setUsers((current) => current.filter((user) => user.id !== target.id)); setTarget(null); deleteDialog.current?.close(); };
  const resetPassword = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (!passwordTarget) return; setSaving(true); setFormError(""); const password = String(new FormData(form).get("password") || ""); const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: passwordTarget.id, password }) }); const body = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) { setFormError(body.error || "Unable to reset password."); return; } setShowPassword(false); resetDialog.current?.close(); form.reset(); setPasswordTarget(null); };
  const editAccount = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (!editTarget) return; setSaving(true); setFormError(""); const values = new FormData(form); const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "edit", id: editTarget.id, name: String(values.get("name") || ""), email: String(values.get("email") || ""), role: String(values.get("role") || ""), status: String(values.get("status") || "") }) }); const body = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) { setFormError(body.error || "Unable to update account."); return; } setUsers((current) => current.map((user) => user.id === body.user.id ? { ...body.user, last_login: user.last_login } : user)); editDialog.current?.close(); form.reset(); setEditTarget(null); };
  return <>
    <header className="admin-content-toolbar"><p>Workspace users</p><button className="admin-add primary-btn" type="button" onClick={() => { setFormError(""); addDialog.current?.showModal(); }}><i className="fa-solid fa-user-plus" aria-hidden="true" /> Add User</button></header>
    {error && <p className="admin-error" role="alert">{error}</p>}
    <section className="admin-card" aria-label="Users"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="admin-empty">Loading users…</td></tr> : users.length ? users.map((user) => <tr key={user.id}><td><div className="admin-person">{user.name}<small>Workspace user</small></div></td><td>{user.email}</td><td className="admin-role">{title(user.role)}</td><td><span className={`admin-status ${user.status}`}>{title(user.status)}</span></td><td>{date(user.last_login)}</td><td><div className="admin-row-actions"><button type="button" className="admin-reset" onClick={() => { setFormError(""); setEditTarget(user); editDialog.current?.showModal(); }}>Edit</button><button type="button" className="admin-reset" onClick={() => { setFormError(""); setPasswordTarget(user); resetDialog.current?.showModal(); }}>Reset password</button><button type="button" className="admin-delete" onClick={() => { setTarget(user); deleteDialog.current?.showModal(); }}>Delete</button></div></td></tr>) : <tr><td colSpan={6} className="admin-empty">No active users. Add first workspace user.</td></tr>}</tbody></table></div></section>
    <dialog className="admin-dialog" ref={addDialog} aria-labelledby="addUserTitle"><form onSubmit={create}><h2 id="addUserTitle">Add User</h2><p>Create a new PurityLoop AI account and assign its access role.</p><p className="admin-dialog-helper">Set the password this user will use to sign in.</p><div className="admin-form-grid"><div className="admin-field wide"><label htmlFor="adminName">Name</label><input id="adminName" name="name" autoComplete="name" required autoFocus /></div><div className="admin-field wide"><label htmlFor="adminEmail">Email</label><input id="adminEmail" name="email" type="email" autoComplete="email" required /></div><div className="admin-field wide"><label htmlFor="adminPassword">Password</label><div className="admin-password-wrap"><input id="adminPassword" name="password" type={showPassword ? "text" : "password"} minLength={8} autoComplete="new-password" required /><button type="button" onClick={() => setShowPassword((visible) => !visible)} aria-label={showPassword ? "Hide password" : "Show password"} aria-pressed={showPassword}><i className={`fa-solid ${showPassword ? "fa-eye-slash" : "fa-eye"}`} aria-hidden="true" /></button></div></div><div className="admin-field"><label htmlFor="adminRole">Role</label><select id="adminRole" name="role" defaultValue="operator">{ROLES.map((role) => <option key={role} value={role}>{title(role)}</option>)}</select></div><div className="admin-field"><label htmlFor="adminStatus">Status</label><select id="adminStatus" name="status" defaultValue="active"><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div>{formError && <p className="admin-form-error" role="alert">{formError}</p>}<div className="admin-dialog-actions"><button type="button" className="admin-cancel" onClick={() => addDialog.current?.close()}>Cancel</button><button className="admin-confirm" disabled={saving}>{saving ? "Adding…" : "Add User"}</button></div></form></dialog>
    <dialog className="admin-dialog" ref={deleteDialog} aria-labelledby="deleteUserTitle"><div className="admin-dialog-content"><h2 id="deleteUserTitle">Delete this user?</h2><p>This account will no longer be able to sign in to PurityLoop AI.</p><div className="admin-dialog-actions"><button type="button" className="admin-cancel" onClick={() => deleteDialog.current?.close()}>Cancel</button><button type="button" className="admin-confirm danger" disabled={saving} onClick={() => void remove()}>{saving ? "Deleting…" : "Delete User"}</button></div></div></dialog>
    <dialog className="admin-dialog" ref={editDialog} aria-labelledby="editAccountTitle"><form key={editTarget?.id} onSubmit={editAccount}><h2 id="editAccountTitle">Edit account</h2><p>Update workspace access and account details.</p><div className="admin-form-grid"><div className="admin-field wide"><label htmlFor="editName">Name</label><input id="editName" name="name" defaultValue={editTarget?.name} required autoFocus /></div><div className="admin-field wide"><label htmlFor="editEmail">Email</label><input id="editEmail" name="email" type="email" defaultValue={editTarget?.email} required /></div><div className="admin-field"><label htmlFor="editRole">Role</label><select id="editRole" name="role" defaultValue={editTarget?.role || "operator"}>{ROLES.map((role) => <option key={role} value={role}>{title(role)}</option>)}</select></div><div className="admin-field"><label htmlFor="editStatus">Status</label><select id="editStatus" name="status" defaultValue={editTarget?.status || "active"}><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div>{formError && <p className="admin-form-error" role="alert">{formError}</p>}<div className="admin-dialog-actions"><button type="button" className="admin-cancel" onClick={() => editDialog.current?.close()}>Cancel</button><button className="admin-confirm" disabled={saving}>{saving ? "Saving…" : "Save changes"}</button></div></form></dialog>
    <dialog className="admin-dialog" ref={resetDialog} aria-labelledby="resetPasswordTitle"><form onSubmit={resetPassword}><h2 id="resetPasswordTitle">Reset password</h2><p>Set a new password for {passwordTarget?.email}.</p><div className="admin-form-grid"><div className="admin-field wide"><label htmlFor="resetPassword">Password</label><div className="admin-password-wrap"><input id="resetPassword" name="password" type={showPassword ? "text" : "password"} minLength={8} autoComplete="new-password" required autoFocus /><button type="button" onClick={() => setShowPassword((visible) => !visible)} aria-label={showPassword ? "Hide password" : "Show password"} aria-pressed={showPassword}><i className={`fa-solid ${showPassword ? "fa-eye-slash" : "fa-eye"}`} aria-hidden="true" /></button></div></div></div>{formError && <p className="admin-form-error" role="alert">{formError}</p>}<div className="admin-dialog-actions"><button type="button" className="admin-cancel" onClick={() => resetDialog.current?.close()}>Cancel</button><button className="admin-confirm" disabled={saving}>{saving ? "Saving…" : "Reset password"}</button></div></form></dialog>
  </>;
}
